# Generated by Django 3.1 on 2020-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='portfolio/logo')),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('position', models.CharField(max_length=500)),
                ('role_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
