# Generated by Django 3.1 on 2020-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200820_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('gpa', models.IntegerField()),
                ('logo', models.ImageField(upload_to='portfolio/logo')),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('activities', models.ManyToManyField(null=True, to='portfolio.activity')),
            ],
        ),
    ]
