# Generated by Django 3.1 on 2020-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.ManyToManyField(to='portfolio.activity'),
        ),
    ]
