# Generated by Django 3.1 on 2020-08-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200820_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.ManyToManyField(blank=True, to='portfolio.activity'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
