# Generated by Django 3.1 on 2020-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200820_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(null=True, upload_to='portfolio/logo'),
        ),
    ]
