# Generated by Django 3.1 on 2020-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200821_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
