# Generated by Django 3.1 on 2020-08-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200822_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='location',
        ),
    ]
