# Generated by Django 3.1 on 2020-08-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_education_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(upload_to='media/portfolio/logo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/portfolio/logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/portfolio/logo'),
        ),
    ]
