# Generated by Django 3.1 on 2020-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200825_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(upload_to='education/logo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(null=True, upload_to='experience/logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/logo'),
        ),
    ]
